[workspace]
authors = ["Tyler C. Sutterley"]
channels = ["conda-forge"]
name = "tsutterley.github.io"
platforms = ["linux-64"]
version = "2026"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tasks.webserver]
args = [{ "arg" = "port", "default" = "1313" }]
cmd = "hugo server --disableFastRender --port {{ port }}"
description = "Locally build and serve the site with hugo"

[tasks.build]
args = [{ "arg" = "flags", "default" = "" }]
cmd = "hugo --gc --minify {{ flags }}"
description = "Build the site for deployment with hugo"

[feature.dev.tasks.lint]
args = [
    { "arg" = "flags", "default" = "--select=E9,F63,F7,F82 --show-source" },
    { "arg" = "test", "default" = "." },
]
cmd = "flake8 {{ test }} --count {{ flags }} --statistics --extend-exclude 'build/,.pixi/'"
description = "Run flake8 to check for compilation errors"

[feature.dev.tasks.test]
cmd = "pytest --verbose --capture=no test_*"
cwd = "static/data"
description = "Run pytest to check fonts and cartopy installations"

[feature.dev.tasks.fetch]
args = [
    { "arg" = "directory", "default" = "--directory ." },
    { "arg" = "center", "default" = "--center CSR GFZ JPL" },
    { "arg" = "release", "default" = "--release RL06" },
    { "arg" = "version", "default" = "--version 0 3" },
    { "arg" = "flags", "default" = "--timeout=3600 --log --np=0" },

]
cmd = "python podaac_cumulus.py {{ directory }} {{ center }} {{ version }} {{ flags }}"
cwd = "static/data"
description = "Fetch GRACE/GRACE-FO data from PO.DAAC"

[feature.dev.tasks.podaac-date]
args = [
    { "arg" = "directory", "default" = "--directory ." },
    { "arg" = "release", "default" = "--release RL06" },
    { "arg" = "product", "default" = "--product GSM" },

]
cmd = "grace_date.py {{ directory }} {{ release }} {{ product }} --output"
cwd = "static/data"
description = "Run GRACE/GRACE-FO date programs"

[feature.dev.tasks.gsfc-date]
args = [
    { "arg" = "directory", "default" = "--directory ." },
    { "arg" = "version", "default" = "--version rl06v2.0" },

]
cmd = "python GSFC_grace_date.py {{ directory }} {{ version }}"
cwd = "static/data"
description = "Run GRACE/GRACE-FO GSFC date programs"

[feature.dev.tasks.date-index]
args = [
    { "arg" = "directory", "default" = "--directory ." },
    { "arg" = "release", "default" = "--release RL06 rl06v2.0" },

]
cmd = "grace_months_index.py {{ directory }} {{ release }}"
cwd = "static/data"
depends-on = ["podaac-date", "gsfc-date"]
description = "Make the GRACE/GRACE-FO date index file"

[feature.dev.tasks.update-cycles]
cmd = "python icesat2_cycles_table.py"
cwd = "static/data"
description = "Update the ICESat-2 cycles markdown table"

[feature.dev.tasks.update-tables]
cmd = "bash update_tables.sh"
cwd = "static/data"
description = "Update the GRACE months markdown table"

[dependencies]
# Golang open-source programming language
go = "*"
# extended version of the Hugo static site generator
hugo = "==0.164.0"
# pandoc for bibliographies
pandoc = "*"

[feature.dev.dependencies]
flake8 = "*"
gh = "*"
gravity-toolkit = "*"
pytest = "*"
pytest-cov = "*"
