[workspace]
authors = ["Tyler Sutterley <tsutterl@uw.edu>"]
channels = ["conda-forge"]
name = "tsutterley.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.lint]
args = [ { "arg" = "flags", "default" = "--select=E9,F63,F7,F82 --show-source" }, { "arg" = "test", "default" = "." } ]
cmd = "flake8 {{ test }} --count {{ flags }} --statistics --extend-exclude 'build/,.pixi/'"
description = "Run flake8 to check for compilation errors"

[tasks.fetch]
args = [ 
    { "arg" = "directory", "default" = "--directory ." }, 
    { "arg" = "center", "default" = "--center CSR GFZ JPL" },
    { "arg" = "release", "default" = "--release RL06" },
    { "arg" = "version", "default" = "--version 0 3" },
    { "arg" = "flags", "default" = "--timeout=3600 --log --np=0"}

]
cmd = "python podaac_cumulus.py {{ directory }} {{ center }} {{ version }} {{ flags }}"
cwd = "data"
description = "Fetch GRACE/GRACE-FO data from PO.DAAC"

[tasks.podaac-date]
args = [ 
    { "arg" = "directory", "default" = "--directory ." }, 
    { "arg" = "release", "default" = "--release RL06" },
    { "arg" = "product", "default" = "--product GSM" },

]
cmd = "grace_date.py {{ directory }} {{ release }} {{ product }} --output"
cwd = "data"
description = "Run GRACE/GRACE-FO date programs"

[tasks.gsfc-date]
  args = [ 
    { "arg" = "directory", "default" = "--directory ." }, 
    { "arg" = "version", "default" = "--version rl06v2.0" },

]
cmd = "python GSFC_grace_date.py {{ directory }} {{ version }}"
cwd = "data"
description = "Run GRACE/GRACE-FO GSFC date programs"

[tasks.date-index]
args = [ 
    { "arg" = "directory", "default" = "--directory ." }, 
    { "arg" = "release", "default" = "--release RL06 rl06v2.0" },

]
cmd = "grace_months_index.py {{ directory }} {{ release }}"
cwd = "data"
depends-on = ["podaac-date", "gsfc-date"]
description = "Make the GRACE/GRACE-FO date index file"

[tasks.update-tables]
cmd = "bash update_tables.sh"
cwd = "data"
description = "Update the html table and images"

[tasks.update-lfs-attributes]
cmd = "python data/git_lfs_attributes.py --directory images/ --regex '^(CSR|GFZ|GSFC|JPL)-(.*?)-(\\d+).jpg'"
description = "Update the git-lfs attributes file"

[dependencies]
gravity-toolkit = "*"
pytest = "*"
flake8 = "*"
