# This workflow will install Python dependencies and update the html tables

name: Auto-Update Tables

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      PODAAC_PASSWORD: ${{ secrets.PODAAC_PASSWORD }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-fonts-extra texlive-font-utils cm-super dvipng font-manager
        sudo ln -sv $PWD/assets/fonts/Helvetica /usr/share/fonts/truetype
    - name: Set up pixi environment
      uses: prefix-dev/setup-pixi@v0.9.1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pixi run lint
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pixi run lint "--exit-zero --max-complexity=10 --max-line-length=127"
    - name: Test with pytest
      run: |
        pixi run pytest --verbose --capture=no data/test_font_files.py
        pixi run pytest --verbose --capture=no data/test_cartopy.py
    - name: Download GRACE/GRACE-FO data
      run: |
        pixi run fetch
        pixi run date-index
    - name: Archive GRACE/GRACE-FO dates
      uses: actions/upload-artifact@v4
      with:
        name: grace-months
        path: |
            data/PODAAC_sync.log
            data/GRACE_months.txt
    - name: Check for updates
      id: changes
      run: |
        if [ -n "$(git status --porcelain data/GRACE_months.txt)" ] ; then
            echo "DETECTED=true" >> $GITHUB_OUTPUT;
            echo "::debug::Changes detected";
        else
            echo "DETECTED=false" >> $GITHUB_OUTPUT;
            echo "::debug::No changes detected";
        fi
    - name: Update GRACE/GRACE-FO tables
      if: steps.changes.outputs.DETECTED == 'true'
      run: |
        pixi run update-tables
        pixi run update-lfs-attributes
    - name: Commit changes
      if: steps.changes.outputs.DETECTED == 'true'
      run: |
        git config user.name 'Github Actions'
        git config user.email 'actions@github.com'
        git add .gitattributes data/GRACE-Months.html data/GRACE_months.txt images/*.jpg
        git commit -am "Automatic table updates"
    - name: Create pull request
      if: steps.changes.outputs.DETECTED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        assignees: ${{ github.actor }}
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: "Automatic table updates"
